# Generated by Django 5.1.2 on 2025-09-12 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendancePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
                (
                    "attend",
                    models.CharField(
                        choices=[("attend", "出席"), ("absent", "欠席")],
                        default="absent",
                        max_length=50,
                    ),
                ),
                ("unit_teach_price", models.IntegerField(default=1000)),
                ("unit_room_price", models.IntegerField(default=100)),
                ("room_price", models.FloatField()),
                ("extra_income", models.IntegerField(default=0)),
                ("extra_outgo", models.IntegerField(default=0)),
                ("memo", models.TextField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.member"
                    ),
                ),
            ],
        ),
    ]
