# Generated by Django 5.1.2 on 2025-09-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_attendancepayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancepayment",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="attendancepayment",
            name="memo",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="attendancepayment",
            name="room_price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
