# Generated by Django 5.1.2 on 2025-09-12 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_attendancepayment_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendancepayment",
            name="attend",
        ),
        migrations.RemoveField(
            model_name="attendancepayment",
            name="member_id",
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("attend", "参加"), ("absent", "不参加")],
                        default="absent",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.member"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "participants",
                    models.ManyToManyField(
                        through="account.Attendance", to="account.member"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="attendance",
            name="meeting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.meeting"
            ),
        ),
    ]
