# Generated by Django 5.1.2 on 2025-09-12 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_remove_attendancepayment_attend_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendancepayment",
            name="date",
        ),
        migrations.AddField(
            model_name="attendancepayment",
            name="meeting",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="account.meeting",
            ),
            preserve_default=False,
        ),
    ]
