# Generated by Django 5.1.2 on 2025-09-18 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_remove_attendancepayment_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="date",
        ),
    ]
