# Generated by Django 5.1.2 on 2025-09-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_remove_meeting_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="meeting",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="user",
        ),
        migrations.RemoveField(
            model_name="attendancepayment",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="attendancepayment",
            name="extra_income",
        ),
        migrations.RemoveField(
            model_name="attendancepayment",
            name="extra_outgo",
        ),
        migrations.RemoveField(
            model_name="attendancepayment",
            name="meeting",
        ),
        migrations.RemoveField(
            model_name="attendancepayment",
            name="memo",
        ),
        migrations.RemoveField(
            model_name="attendancepayment",
            name="room_price",
        ),
        migrations.RemoveField(
            model_name="attendancepayment",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="participants",
        ),
        migrations.AddField(
            model_name="meeting",
            name="unit_teach_price",
            field=models.IntegerField(default=1000),
        ),
    ]
