# Generated by Django 5.1.2 on 2025-09-18 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_remove_attendance_meeting_remove_attendance_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attendance",
        ),
        migrations.DeleteModel(
            name="AttendancePayment",
        ),
        migrations.DeleteModel(
            name="Meeting",
        ),
    ]
