# Generated by Django 5.1.2 on 2025-09-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_delete_attendance_delete_attendancepayment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "participants",
                    models.CharField(
                        choices=[("attend", "参加"), ("absent", "不参加")],
                        default="absent",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_teach_price", models.IntegerField(default=1000)),
                ("unit_room_price", models.IntegerField(default=100)),
                ("room_price", models.FloatField(blank=True, null=True)),
                ("extra_income", models.IntegerField(default=0)),
                ("extra_outgo", models.IntegerField(default=0)),
                ("memo", models.TextField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
