# Generated by Django 5.1.2 on 2025-09-18 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_event_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="member",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.member",
            ),
            preserve_default=False,
        ),
    ]
