# Generated by Django 5.1.2 on 2025-09-18 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_event_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="event",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.event",
            ),
            preserve_default=False,
        ),
    ]
