# Generated by Django 5.1.2 on 2025-09-18 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_payment_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="account.event",
                unique=True,
            ),
        ),
    ]
